---
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
#  process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Bear Dukes Luxembourg"
tagline: "The first bear community in Luxembourg"
description: >- # this means to ignore newlines until "baseurl:"
  We are the Luxembourgish bear community ðŸ‡±ðŸ‡º:bear:.
url: "https://bears.lu"
author: Bear Dukes Luxembourg a.s.b.l.
twitter:
  card: summarry
# username:
facebook:
  publisher: 1385637221689399
#  admins:
#  app_id:
logo: "/assets/Bear Dukes Luxembourg.png"
social:
  name: Thibault M.
  links:
    - https://twitter.com/clawfire
    - https://github.com/clawfire
    - https://keybase.io/thibault
    - https://www.facebook.com/thibault.milan.1
webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""
lang: "en_US"

permalink: "/news/:year/:month/:day/:title/"
baseurl: "/"
email: contact@bears.lu

bearpride:
  enabled: true #that will display the bear pride panel on homepage
  homepage_panel:
    title: "Bear Pride Luxembourg 2023"
    description: |-
      On Oct. 6-7-8, it's the Bear Pride in Luxembourg city. Clubbing, social activities, Mr Bear election, city tour ...
      all you need to know about the event is here. The Bear Pride in Luxembourg city is a three-day event that celebrates the
      LGBTQ+ community and the bear subculture. On Oct. 6th, the festivities kick off with a bear night at the cityâ€™s newest
      popular gay bar, followed by a social gathering on Oct. 7th. On the same day, the Mr Bear election will take place, where the
      winner will be crowned the Bear of Luxembourg. Whether youâ€™re a bear, a cub, or an ally, the Bear Pride in Luxembourg city is the
      perfect opportunity to celebrate diversity and have a great time.
  facebook_main_event: https://fb.me/e/2DKQ8CGAU
  combo_ticket_url:
  application_open: true
  candidate_list: false
  hotel_cta:
    display: false
    content: |-
      Our partner, INNSiDE by MeliÃ , is excited to welcome you in their
      brand new hotel in Cloche d'Or, the vibrant and fast growing new neighborhood
      in Luxembourg-city.
      All rooms includes Breakfast.
    url: https://tally.so/r/nGZ0pw

pagination:
  enabled: true
  debug: true
  per_page: 10
  sort_reverse: true
  # The permalink structure for the paginated pages (this can be any level deep)
  # permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  # permalink: '/page/:num.html' # Pages are simple html files
  permalink: '/page/:num'
  # Pages are html files, linked jekyll extensionless permalink style.


# social:
#  facebook: "https://www.facebook.com/luxembourgbears/"
#  facebookgroup: "https://www.facebook.com/groups/beardukes/"
# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-twitter-plugin
  - jekyll-youtube
  - jemoji
  - jekyll-paginate-v2
  - jekyll-seo-tag
sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
